# Generated by Django 4.0.6 on 2022-08-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_vehicle_office'),
        ('users', '0006_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='companies.office'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='driver', to='companies.vehicle'),
        ),
    ]
