# Generated by Django 4.0.6 on 2022-07-31 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_office_city_alter_office_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.office'),
        ),
    ]
