# Generated by Django 4.0.6 on 2022-08-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_vehicle_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='office',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vehicles', to='companies.office'),
        ),
    ]
